networks:
  backend-simple:
    name: backend-simple

services:
  simple:
    container_name: postgres-simple
    image: postgres:16beta3-bullseye
    restart: always
    environment:
      POSTGRES_DB: simple
      POSTGRES_USER: jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./server.crt:/var/lib/postgresql/server.crt:ro
      - ./server.key:/var/lib/postgresql/server.key:ro
    networks:
      - backend-simple
    command: >
      -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
