
zio-pgcopy:
  server:
    host           : localhost
    port           : 5432
    sslmode        : disable # disable | trust | runtime 
    database       : facts
    user           : jimmy
    password       : banana

  pool:
    min            : 32
    max            : 32
    timeout        : 15.minutes

  retry:
    base           : 200.milliseconds
    factor         : 1.33
    retries        : 10

  io:
    so_sndbuf      : 32768  
    so_rcvbuf      : 32768
    bytebufsize    : 8000000
    bufsizecheck   : false  
    incomingsize   : 32768
    outgoingsize   : 32768
