
zio-pgcopy:
  server:
    host           : localhost
    port           : 5432
    sslmode        : disable # disable | trust | runtime 
    database       : world
    user           : jimmy
    password       : banana

  pool:
    min            : 16
    max            : 16
    timeout        : 15.minutes

  retry:
    base           : 100.milliseconds
    factor         : 1.25
    retries        : 25

  io:
    so_sndbuf      : 32768 
    so_rcvbuf      : 32768
    bytebufsize    : 8388608
    incomingsize   : 8192
    outgoingsize   : 4096
