networks:
  backend:
    name: backend

services:
  world:
    container_name: postgres-example1
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_DB: world
      POSTGRES_USER: jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./server.crt:/var/lib/postgresql/server.crt:ro
      - ./server.key:/var/lib/postgresql/server.key:ro
    networks:
      - backend
    command: >
      -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
